language: cpp
dist: bionic
sudo: require
compiler: gcc

install: 
  - sudo apt update -qq
  # Boost
  - sudo apt install -qq libboost-all-dev
  # CMake
  - wget --no-check-certificate https://cmake.org/files/v3.8/cmake-3.8.1-Linux-x86_64.tar.gz -O $HOME/cmake.tar.gz && tar xf $HOME/cmake.tar.gz -C $HOME && rm $HOME/cmake.tar.gz
  - export PATH=$HOME/cmake-3.8.1-Linux-x86_64/bin:$PATH
  - sudo apt-get update -qq
  # Urho3D
  - sudo apt-get install libx11-dev libxrandr-dev libasound2-dev libgl1-mesa-dev
  - sudo apt-get install libsdl1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-ttf2.0-dev libxext-dev

services:
  - xvfb

script: 
 # Urho3D
 - ./install_urho3d
 # Build, run and close the executable
 - qmake travis_qmake_gcc_cpp14_urho3d.pro
 - make
 - ls
 - ./travis_qmake_gcc_cpp14_urho3d &
 - sleep 10
 - sudo killall travis_qmake_gcc_cpp14_urho3d

