#!/bin/sh

cd ..

if [ ! -d Urho3D ]
then
  git clone https://github.com/Urho3D/Urho3D
fi

cd Urho3D 
cd script
./cmake_generic.sh  ../
cd ..
make
cd Source
cd ThirdParty
cd Bullet
make

ln -s ./Urho3D/bin/Data
ln -s ./Urho3D/bin/CoreData

cd ..
cd ..
cd ..
cd travis_qmake_gcc_cpp14_urho3d